### ISSUE TITLE
V2.0 Roadmap

### ISSUE THREAD

**Issue by joechenrh** [joechenrh/sudoku-qt#1]
- [ ] support multiple choice
- [ ] create puzzle from images
- [ ] randomly generate puzzle
